### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by twof** [miroslavkovac/Lingo#2]
Sweet framework! I was wondering if it can be used in iOS projects, and if so, are there any plans to support cocoapods?

**Comment by miroslavkovac** [comment]
Hi @twof, thanks for the feedback! :) 

Currently even the Apple's SPM doesn't support iOS, so the only alternative to get Lingo to iOS would be using CocoaPods or Carthage.

Although Lingo was primarily intended to be used on server side swift projects, I can imaging it being used on iOS as well, but unfortunately this is not a priority in the short term.

**Comment by twof** [comment]
ahhh okay. Thanks!
